
DB_USER=daoudi_abdellah
DB_PASSWORD=FBi521rG9n9G4T6fW0Iqm4t4rN0lHWfU
DB_HOST=dpg-d3olcad6ubrc73c9jdig-a.oregon-postgres.render.com      
DB_PORT=5432
DB_NAME=planitor_db


DATABASE_URL=postgresql://daoudi_abdellah:FBi521rG9n9G4T6fW0Iqm4t4rN0lHWfU@dpg-d3olcad6ubrc73c9jdig-a/planitor_db


SECRET_KEY=SSSeeeccc111999999666666999999@@@ABDO
DEBUG=False
SESSION_TIMEOUT=120        # minutes



LOG_DIR=logs
OUTPUT_DIR=outputs
TEMPLATE_DIR=templates
BACKUP_DIR=backups


SCHEMA_VERSION=2.0.0
